name=Gypsy
version=1.0.0
author=Dwan
maintainer=Dwan
sentence=IOT sensor node
paragraph=Plug your sensor shield and connect it to the web
category=Communication
url=https://github.com/Gypsy-Server/Gypsyv1
architectures=esp8266
depends=ArduinoJson
